/* eslint-disable @next/next/no-html-link-for-pages -- Enter forms with document navigation so browser Back triggers the native unsaved-changes guard. */
import type { WeddingEvent } from "@/modules/events/schemas";
import { eventDayLabel, eventTimeRange, upcomingEvents } from "@/modules/events/dates";
import Link from "next/link";
import type { getWeddingContext } from "@/modules/weddings/service";
import { daysUntilWedding, weddingDateLabel } from "@/modules/weddings/dates";
import { WeddingCountdown } from "./countdown";
import { timeZoneLabel } from "./time-zones";
import { Icon } from "@/components/home/icon";
import { FeaturePreviewButton } from "@/components/workspace/feature-preview";
import { sampleStats, sampleTasks } from "@/components/workspace/sample-data";
import styles from "@/components/workspace/workspace.module.css";

type Wedding = NonNullable<Awaited<ReturnType<typeof getWeddingContext>>["wedding"]>;
export type WorkspaceMember = { id: string; name: string; role: string };
export function OverviewPage({ wedding, updated = false, members = [], role, events = [] }: { wedding: Wedding; updated?: boolean; members?: WorkspaceMember[]; role?: string; events?: WeddingEvent[] }) {
  const activeEvents = events.filter(event => !event.archivedAt);
  const upcoming = upcomingEvents(activeEvents);
  const location = wedding.location.formattedAddress || [wedding.location.city, wedding.location.state, wedding.location.country].filter(Boolean).join(", ");
  return <main id="wedding-content" className={styles.dashboard}>
    {updated && <p role="status" className={styles.savedNotice}>Wedding details updated</p>}
    <section className={styles.hero} aria-label="Your wedding details">
      <div className={styles.heroTop}><p className={styles.eyebrow}>Your celebration, beautifully organised</p><span className={styles.countdown}><Icon name="calendar" size={16}/><WeddingCountdown key={`${wedding.weddingDate}:${wedding.timeZone}`} date={wedding.weddingDate} timeZone={wedding.timeZone} initialDays={daysUntilWedding(wedding.weddingDate, wedding.timeZone)}/></span></div>
      <div className={styles.heroMain}><div>{wedding.title && <p className={styles.muted}>{wedding.title}</p>}<h1>{wedding.brideName} <em>&amp;</em> {wedding.groomName}</h1><div className={styles.weddingMeta}><span><Icon name="calendar" size={15}/><time dateTime={wedding.weddingDate}>{weddingDateLabel(wedding.weddingDate)}</time></span>{location && <span><Icon name="location" size={15}/>{location}</span>}<span><Icon name="globe" size={15}/>{timeZoneLabel(wedding.timeZone)}</span></div>{wedding.description && <p className={styles.description}>{wedding.description}</p>}</div><a href="/wedding/edit" className={styles.outline}>Edit wedding details <Icon name="arrow" size={14}/></a></div>
      <div className={styles.collaborators}><span className={styles.eyebrow}>Planning together</span><div className={styles.people}>{members.slice(0, 4).map(member => <span key={member.id} className={styles.person} title={`${member.name} · ${member.role === "ADMIN" ? "Admin" : "Manager"}`}><span className={styles.avatar} aria-hidden="true">{member.name.trim().split(/\s+/).slice(0, 2).map(part => part[0]).join("")}</span>{member.name}</span>)}{members.length > 4 && <span className={styles.muted}>+{members.length - 4} more</span>}</div>{role === "ADMIN" && <Link href="/settings/members" className={styles.textLink}>Manage wedding members →</Link>}</div>
    </section>
    <div className={styles.previewNotice}><Icon name="sparkle" size={20}/><div><strong>Your workspace is taking shape</strong><p>Your wedding details, members, and events use saved data. Other planning sections are labelled as sample previews until their features are available.</p></div></div>
    <section aria-label="Planning summaries" className={styles.statGrid}><article className={styles.statCard}><div className={styles.statTop}><Icon name="calendar" size={19}/></div><p>Wedding events</p><strong>{activeEvents.length}</strong><small>Celebrations in your itinerary</small><Link href="/events" className={styles.textLink}>View events →</Link></article>{sampleStats.map(stat => <article className={styles.statCard} key={stat.feature}><div className={styles.statTop}><Icon name={stat.icon} size={19}/><span className={styles.sampleLabel}>Sample</span></div><p>{stat.label}</p><strong>{stat.value}</strong><small>{stat.detail}</small><FeaturePreviewButton feature={stat.feature} className={styles.textLink}>Coming soon <span aria-hidden="true">→</span></FeaturePreviewButton></article>)}</section>
    <div className={styles.dashboardGrid}><div className={styles.mainColumn}>
      <section className={styles.panel}><div className={styles.panelHead}><div><h2>Your celebrations</h2></div><Link href="/events" className={styles.textLink}>View events →</Link></div><p className={styles.muted}>Upcoming events · {wedding.timeZone}</p><div className={styles.eventList}>{upcoming.map(event => <article className={styles.event} key={event.id}><div className={styles.eventDay}><Icon name="calendar" size={22}/></div><div><h3><Link href={`/events/${event.id}`}>{event.name}</Link></h3><p>{eventDayLabel(event.startsAt, wedding.timeZone)} · {eventTimeRange(event.startsAt, event.endsAt, wedding.timeZone)}</p>{event.venueName && <p>{event.venueName}</p>}{event.dressCode && <span className={styles.attire}>{event.dressCode}</span>}</div><Icon name="arrow" size={16}/></article>)}{!upcoming.length && <><p className={styles.muted}>{activeEvents.length ? "No upcoming events. Your past celebrations are available in Events." : "Add your first event, from Mehendi to the wedding ceremony."}</p><a href="/events/new" className={styles.outline}>+ Add event</a></>}</div></section>
      <section className={styles.panel}><div className={styles.panelHead}><div><p className={styles.sampleLabel}>Sample data — preview</p><h2>A little closer to “I do”</h2></div><FeaturePreviewButton feature="tasks" className={styles.textLink}>Explore tasks →</FeaturePreviewButton></div><p className={styles.muted}>A preview of how your next steps will come together.</p>{sampleTasks.map((task, index) => <div className={styles.task} key={task}><span className={styles.taskCircle} aria-hidden="true"/><div><h3>{task}</h3><p>{index === 1 ? "Wedding Admin" : "Family member"}</p></div><span className={styles.taskStatus}>To do</span></div>)}</section>
    </div><div className={styles.sideColumn}>
      <section className={styles.panel}><p className={styles.sampleLabel}>Sample data — preview</p><h2>Who’s celebrating?</h2><div className={styles.rsvp}><div className={styles.ring} role="img" aria-label="Sample RSVP: 112 attending, 20 declined, 54 awaiting response"><div><strong>132</strong><span>responses</span></div></div><div className={styles.legend}><p><i/>Attending <strong>112</strong></p><p><i/>Declined <strong>20</strong></p><p><i/>Awaiting <strong>54</strong></p></div></div><FeaturePreviewButton feature="invitations" className={styles.textLink}>Explore invitations & RSVP →</FeaturePreviewButton></section>
      <section className={styles.panel}><p className={styles.sampleLabel}>Sample data — preview</p><h2>Wedding expenses</h2><p className={styles.expenseTotal}>₹12,45,000 <small>Total expenses</small></p>{[["Venue", "₹6,50,000"], ["Decorations", "₹2,80,000"], ["Photography", "₹1,75,000"], ["Catering", "₹90,000"], ["Entertainment", "₹50,000"]].map(([name, amount]) => <div className={styles.expense} key={name}><span>{name}</span><strong>{amount}</strong></div>)}<FeaturePreviewButton feature="expenses" className={styles.textLink}>Explore expenses →</FeaturePreviewButton></section>
      <section className={`${styles.panel} ${styles.sharing}`}><Icon name="heart" size={23}/><h2>A celebration worth sharing</h2><p className={styles.muted}>Your wedding website, photo memories, guest QR sharing and livestream will find a home here.</p><div>{(["website", "gallery", "qr", "livestream"] as const).map((feature, index) => <FeaturePreviewButton key={feature} feature={feature} className={styles.outline}>{["Wedding website", "Gallery", "Guest QR", "Livestream"][index]} <span className={styles.sampleLabel}>Soon</span></FeaturePreviewButton>)}</div></section>
    </div></div>
  </main>;
}
