// @vitest-environment happy-dom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { Gallery } from "./gallery";
vi.mock("@/components/wedding/draft-session", () => ({ useWeddingDraftSession: () => ({ revalidate: async () => true, expire }), WeddingDraftNotice: () => null }));
vi.mock("@/components/wedding/unsaved-changes", () => ({ useUnsavedChanges: () => null }));
const expire = vi.fn(); let root: Root, container: HTMLDivElement; const fetcher = vi.fn();
const photo = { id: "photo", url: "https://example.test/photo", eventId: "event", originalFilename: "Wedding.jpg", sizeBytes: 1000, createdAt: "2026-09-18T00:00:00Z", uploaderType: "MEMBER", mimeType: "image/jpeg" };
beforeEach(() => { vi.resetAllMocks(); vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT", true); vi.stubGlobal("fetch", fetcher); vi.spyOn(HTMLDialogElement.prototype, "showModal").mockImplementation(function(this: HTMLDialogElement) { this.open = true; }); vi.spyOn(HTMLDialogElement.prototype, "close").mockImplementation(function(this: HTMLDialogElement) { this.open = false; }); container = document.createElement("div"); document.body.append(container); root = createRoot(container); });
afterEach(async () => { await act(async () => root.unmount()); container.remove(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
async function render() { await act(async () => { root.render(<Gallery events={[{ id: "event", name: "Mehendi", archived: false }]}/>); await new Promise(resolve => setTimeout(resolve, 0)); }); }
async function click(label: string) { const button = [...container.querySelectorAll("button")].find(button => button.textContent === label || button.getAttribute("aria-label") === label)!; expect(button).toBeTruthy(); await act(async () => { button.click(); await new Promise(resolve => setTimeout(resolve, 0)); }); }
const page = (data = [photo]) => Response.json({ data, total: data.length, pagination: { nextCursor: null } });
it("keeps a failed deletion visible for retry, without reporting success", async () => { fetcher.mockImplementation(async (_url, options) => options?.method === "DELETE" ? Response.json({ error: { message: "Storage is unavailable" } }, { status: 503 }) : page()); await render(); await click("View Wedding.jpg"); await click("Delete photo"); const button = container.querySelector<HTMLDialogElement>('[aria-labelledby="delete-title"]')!.querySelectorAll("button")[1]; await act(async () => { button.click(); await new Promise(resolve => setTimeout(resolve, 0)); }); expect(container.querySelector<HTMLDialogElement>('[aria-labelledby="delete-title"]')!.open).toBe(true); expect(container.textContent).toContain("Storage is unavailable"); expect(container.textContent).not.toContain("Photo deleted."); expect(container.querySelector('[aria-label="View Wedding.jpg"]')).not.toBeNull(); });
it("ignores an older filter response after a newer request wins", async () => { let respond: (value: Response) => void = () => {}; fetcher.mockImplementationOnce(() => new Promise(resolve => { respond = resolve; })).mockResolvedValue(page([])); await render(); await click("Mehendi"); expect(container.textContent).toContain("No photos here yet"); await act(async () => respond(page())); expect(container.querySelector('[aria-label="View Wedding.jpg"]')).toBeNull(); expect(fetcher.mock.calls[1][0]).toContain("eventId=event"); });
it("deduplicates cursor pages and keeps earlier photos after a pagination error", async () => { fetcher.mockResolvedValueOnce(Response.json({ data: [photo], total: 2, pagination: { nextCursor: "next" } })).mockResolvedValueOnce(Response.json({ error: { message: "Offline" } }, { status: 503 })).mockResolvedValueOnce(Response.json({ data: [photo, { ...photo, id: "second", originalFilename: "Dance.jpg" }], total: 2, pagination: { nextCursor: null } })); await render(); await click("Load more photos ↓"); expect(container.textContent).toContain("Offline"); expect(container.querySelector('[aria-label="View Wedding.jpg"]')).not.toBeNull(); await click("Try again"); expect(container.querySelectorAll('[aria-label="View Wedding.jpg"]')).toHaveLength(1); expect(container.querySelector('[aria-label="View Dance.jpg"]')).not.toBeNull(); });
